### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by Madses** [aalexgabi/node-adwords-es5#2]
I am having trouble finding where to get a refresh token for Adwords, it would be nice if you could help me out.

**Comment by aalexgabi** [comment]
I don't believe this library has a way to get a refresh token. Here is the way I get one: https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library

**Comment by aalexgabi** [comment]
Here are some alternatives: https://developers.google.com/adwords/api/docs/guides/first-api-call#get_an_oauth2_refresh_token_and_configure_your_client

**Comment by aalexgabi** [comment]
Here are some alternatives: https://developers.google.com/adwords/api/docs/guides/first-api-call#get_an_oauth2_refresh_token_and_configure_your_client
