### ISSUE TITLE
Refresh token for nodejs

### ISSUE THREAD

**Issue by Madses** [aalexgabi/node-adwords-es5#3]
To generate a refresh token there are several guides. Those guides however are only for the PHP,PythonRuby, .NET. The Php one looks like this. 

https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library

I'm wondering how i could generate one using your library.

**Comment by aalexgabi** [comment]
I don't believe this library has a way to get a refresh token. Here is the way I get one: https://github.com/googleads/googleads-php-lib/wiki/API-access-using-own-credentials-(installed-application-flow)#step-2---setting-up-the-client-library
