### ISSUE TITLE
TargetingIdeaService error

### ISSUE THREAD

**Issue by Madses** [aalexgabi/node-adwords-es5#4]
Hi I have been trying to get this code to work without success, it would be nice if u could give this a look, been stuck on this!

```
var TargetingIdeaService = user.getService('TargetingIdeaService', 'v201609')

//create selector 
var selector={
    SearchParameter:[{RelatedToQuerySearchParameter:'Games'}],
    IdeaType:'KEYWORDS',
    requestType:'IDEAS',
    requestedAttributeTypes: ['TARGETED_MONTHLY_SEAsRCHES', 'KEYWORD_TEXT'],
    paging: {startIndex: 0, numberResults:20}
}
 
TargetingIdeaService.get({serviceSelector: selector}, function (error, result) {
    console.log(error, result);
}) 

```
UPDATED:

```
var TargetingIdeaService = user.getService('TargetingIdeaService', 'v201609')

//create selector 
var selector={
    searchParameters:{
    	RelatedToQuerySearchParameter:[{queries:['TEST']}],
    },
    ideaType:'KEYWORD',
    requestType:'IDEAS',
    requestedAttributeTypes: ['KEYWORD_TEXT'],
    paging: {startIndex: 0, numberResults:20}  
}

 
TargetingIdeaService.get({TargetingIdeaSelector: selector}, function (error, result) {
    console.log(error, result);
}) 
```

**Comment by aalexgabi** [comment]
@Madses Can you also post the error you get?

I'm not sure if this is a problem but note that there is a lower case "s" in "TARGETED_MONTHLY_SEAsRCHES".

**Comment by Madses** [comment]
Hi, 

I updated my code because there were a couple of things that i found wrong with it. atm i don't see any other mistakes in it but i still get this error:

```
'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><
soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalli
ng Error: ParseError at [row,col]:[1,833]\nMessage: http://www.w3.org/TR/1999/RE
C-xml-names-19990114#ElementPrefixUnbound?ns1&amp;ns1:TargetingIdeaSelector </fa
ultstring></soap:Fault></soap:Body></soap:Envelope>
```

Its actually a lot more but i think this is the relevant part.

**Comment by Madses** [comment]
Using this documentation https://developers.google.com/adwords/api/docs/reference/v201609/TargetingIdeaService.TargetingIdeaSelector

**Comment by aalexgabi** [comment]
@Madses Sorry but I don't know how this works. I never used all features of this library. I just ported this project to ES5. You may be able to get some help from the original project maintainers: https://github.com/ChrisAlvares/node-adwords
